# Generated by Django 5.1.7 on 2025-03-28 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('title_kana', models.CharField(max_length=200)),
                ('media', models.CharField(max_length=200)),
                ('episodes_count', models.IntegerField()),
                ('season_year', models.IntegerField()),
                ('season_name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='myapp.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('roletext', models.CharField(max_length=200)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='myapp.anime')),
            ],
        ),
    ]
