# Generated by Django 5.1.7 on 2025-03-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='import_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season_name',
            field=models.CharField(max_length=200),
        ),
    ]
