# Generated by Django 5.1.7 on 2025-03-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_cast_cast_id_alter_cast_name_alter_staff_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='import_type',
        ),
    ]
