# Generated by Django 5.1.7 on 2025-03-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_anime_import_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_id',
            field=models.CharField(max_length=200, verbose_name='アニメID'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes_count',
            field=models.IntegerField(verbose_name='話数'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='media',
            field=models.CharField(max_length=200, verbose_name='メディア'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season_name',
            field=models.CharField(max_length=200, verbose_name='季節'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season_year',
            field=models.IntegerField(verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title_kana',
            field=models.CharField(max_length=200, verbose_name='タイトルカナ'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='キャストID'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='声優名'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='スタッフ名'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='roletext',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='役割'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='スタッフID'),
        ),
    ]
