# Generated by Django 5.1.7 on 2025-03-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_anime_anime_id_alter_anime_episodes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='アニメID'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes_count',
            field=models.IntegerField(default=0, verbose_name='話数'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='季節'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season_year',
            field=models.IntegerField(default=0, verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title_kana',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='タイトルカナ'),
        ),
    ]
