# Generated by Django 5.1.7 on 2025-03-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_anime_anime_id_alter_anime_episodes_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='anime',
            new_name='anime_id',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='anime',
            new_name='anime_id',
        ),
    ]
