# Generated by Django 5.1.7 on 2025-03-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_cast_id_alter_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='anime_cast_id',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='anime_staff_id',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='cast',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
