# Generated by Django 5.1.7 on 2025-03-31 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cast_anime_cast_id_staff_anime_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='anime_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='myapp.anime', to_field='anime_id'),
        ),
    ]
