# Generated by Django 5.1.7 on 2025-03-31 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_cast_anime_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='anime_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='myapp.anime', to_field='anime_id'),
        ),
    ]
