# Generated by Django 5.1.7 on 2025-04-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_staff_anime_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='anime_id',
        ),
        migrations.AddField(
            model_name='cast',
            name='animes',
            field=models.ManyToManyField(related_name='casts', to='myapp.anime'),
        ),
    ]
