# Generated by Django 5.1.7 on 2025-04-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_cast_anime_id_cast_animes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='anime_cast_id',
        ),
        migrations.AddField(
            model_name='cast',
            name='anime_id',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='アニメID'),
        ),
    ]
