# Generated by Django 5.1.7 on 2025-04-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_cast_anime_cast_id_cast_anime_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='タイトル')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='著者')),
                ('desigher', models.CharField(blank=True, max_length=200, null=True, verbose_name='絵師')),
                ('type', models.CharField(blank=True, max_length=200, null=True, verbose_name='分類')),
                ('genre', models.CharField(blank=True, max_length=200, null=True, verbose_name='ジャンル')),
                ('series', models.IntegerField(default=0, verbose_name='巻数')),
                ('list', models.CharField(blank=True, max_length=200, null=True, verbose_name='リスト')),
                ('value', models.CharField(blank=True, max_length=200, null=True, verbose_name='評価')),
            ],
        ),
    ]
