# Generated by Django 5.1.7 on 2025-04-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='ジャンル')),
            ],
        ),
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='状態')),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='分類')),
            ],
        ),
        migrations.CreateModel(
            name='BookValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='評価')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='list',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.IntegerField(default=1, verbose_name='巻数'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='type',
        ),
        migrations.RemoveField(
            model_name='book',
            name='value',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.ManyToManyField(to='myapp.bookstatus', verbose_name='状態'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='myapp.bookgenre', verbose_name='ジャンル'),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.ManyToManyField(to='myapp.booktype', verbose_name='分類'),
        ),
        migrations.AddField(
            model_name='book',
            name='value',
            field=models.ManyToManyField(to='myapp.bookvalue', verbose_name='評価'),
        ),
    ]
