# Generated by Django 5.1.7 on 2025-04-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_bookgenre_bookstatus_booktype_bookvalue_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookValue',
            new_name='Value',
        ),
    ]
