# Generated by Django 5.1.7 on 2025-04-06 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_bookvalue_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desigher',
            new_name='designer',
        ),
    ]
