# Generated by Django 5.1.7 on 2025-04-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_desigher_book_designer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.bookgenre', verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.booktype', verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='book',
            name='value',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.value', verbose_name='評価'),
        ),
    ]
