# Generated by Django 5.1.7 on 2025-04-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_book_genre_alter_book_type_alter_book_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='books_genre', to='myapp.bookgenre', verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.ManyToManyField(related_name='books_status', to='myapp.bookstatus', verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='books_type', to='myapp.booktype', verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='book',
            name='value',
            field=models.ManyToManyField(blank=True, related_name='books_value', to='myapp.value', verbose_name='評価'),
        ),
    ]
