# Generated by Django 5.1.7 on 2025-04-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_book_genre_alter_book_status_alter_book_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='曲名')),
                ('singger', models.CharField(blank=True, max_length=200, null=True, verbose_name='歌手')),
                ('writer', models.CharField(blank=True, max_length=200, null=True, verbose_name='作曲者')),
                ('sing_writer', models.CharField(blank=True, max_length=200, null=True, verbose_name='作詞家')),
                ('editor', models.CharField(blank=True, max_length=200, null=True, verbose_name='編曲者')),
                ('song_write', models.CharField(blank=True, max_length=2000, null=True, verbose_name='歌詞')),
                ('value', models.ManyToManyField(blank=True, related_name='music_value', to='myapp.value', verbose_name='評価')),
            ],
        ),
    ]
