# Generated by Django 5.1.7 on 2025-04-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='状態')),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='status',
            field=models.ManyToManyField(blank=True, related_name='music_status', to='myapp.musicstatus', verbose_name='状態'),
        ),
    ]
