# Generated by Django 5.1.7 on 2025-04-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_musicstatus_music_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='animes',
        ),
        migrations.AlterField(
            model_name='staff',
            name='anime_id',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='アニメID'),
        ),
        migrations.CreateModel(
            name='AnimeCastStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_relation', to='myapp.anime', verbose_name='アニメ')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_relation', to='myapp.cast', verbose_name='キャスト')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_relaiton', to='myapp.staff', verbose_name='スタッフ')),
            ],
        ),
    ]
