# Generated by Django 5.1.7 on 2025-04-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_cast_animes_alter_staff_anime_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='分類')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='状態')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='コメント'),
        ),
        migrations.AddField(
            model_name='anime',
            name='value',
            field=models.ManyToManyField(blank=True, related_name='animes_value', to='myapp.value', verbose_name='評価'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='animes_genre', to='myapp.animegenre', verbose_name='ジャンル'),
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.ManyToManyField(blank=True, related_name='animes_status', to='myapp.animestatus', verbose_name='状態'),
        ),
    ]
