# Generated by Django 5.1.7 on 2025-04-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_animegenre_animestatus_anime_comment_anime_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='anime_staff_id',
        ),
    ]
