# Generated by Django 5.1.7 on 2025-04-12 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_staff_anime_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animecaststaff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_relation', to='myapp.staff', verbose_name='スタッフ'),
        ),
    ]
