# Generated by Django 5.1.7 on 2025-04-12 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_animecaststaff_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='anime_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='anime_id',
        ),
        migrations.AddField(
            model_name='cast',
            name='anime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='myapp.anime', verbose_name='アニメ'),
        ),
        migrations.AddField(
            model_name='staff',
            name='anime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='myapp.anime', verbose_name='スタッフ'),
        ),
        migrations.DeleteModel(
            name='AnimeCastStaff',
        ),
    ]
