# Generated by Django 5.1.7 on 2025-04-12 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_cast_anime_id_remove_staff_anime_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='myapp.anime', verbose_name='アニメ'),
        ),
    ]
