# Generated by Django 5.2 on 2025-04-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_cast_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='media',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='メディア'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='タイトル'),
        ),
    ]
