# Generated by Django 5.2 on 2025-04-21 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_anime_media_alter_anime_season_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='anime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='myapp.anime', verbose_name='アニメ'),
        ),
    ]
