# Generated by Django 5.2 on 2025-04-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_staff_anime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='status',
        ),
        migrations.RemoveField(
            model_name='music',
            name='value',
        ),
        migrations.DeleteModel(
            name='MusicStatus',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
